# Generated by Django 5.0 on 2025-05-12 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('psiquiatria', 'Psiquiatria'), ('fisioterapia', 'Fisioterapia'), ('nutricao', 'Nutrição'), ('fonoaudiologia', 'Fonoaudiologia')], max_length=50)),
                ('efetuado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExameSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sangue', 'Exame de Sangue'), ('raio_x', 'Raio-X'), ('tomografia', 'Tomografia'), ('urina', 'Exame de Urina')], max_length=50)),
                ('efetuado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField(default=datetime.date(2000, 1, 1))),
                ('leito', models.CharField(max_length=10)),
                ('cpf', models.CharField(default='000.000.000-00', max_length=14)),
                ('risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('liberado_para_alta', models.BooleanField(default=False)),
                ('data_agendamento', models.DateField(blank=True, null=True)),
                ('numero_registro', models.CharField(default='REG000', max_length=50)),
                ('especialidade_primeiro_atendimento', models.CharField(blank=True, choices=[('clinica_geral', 'Clínica Geral'), ('cardiologia', 'Cardiologia'), ('neurologia', 'Neurologia'), ('ortopedia', 'Ortopedia'), ('pediatria', 'Pediatria')], max_length=50, null=True)),
                ('hora_primeiro_atendimento', models.TimeField(blank=True, null=True)),
                ('bloco_cirurgico_solicitado', models.BooleanField(default=False)),
                ('leito_solicitado', models.BooleanField(default=False)),
                ('hora_solicitacao', models.TimeField(blank=True, null=True)),
                ('conduta_paciente', models.TextField(blank=True, null=True)),
                ('atendimentos_solicitados', models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.atendimentosolicitado')),
                ('exames_solicitados', models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.examesolicitado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'ordering': ['nome'],
            },
        ),
    ]
