# Generated by Django 5.2.1 on 2025-05-23 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_atendimentosolicitado_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='atendimentos_solicitados',
        ),
        migrations.RemoveField(
            model_name='examesolicitado',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='exames_solicitados',
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='bloco_cirurgico_solicitado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='conduta_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hora_solicitacao',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='leito',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='leito_solicitado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='liberado_para_alta',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_agendamento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Entrada'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidade_primeiro_atendimento',
            field=models.CharField(blank=True, choices=[('CG', 'Clínica Geral'), ('NCR', 'Neurocirurgia'), ('TM', 'Traumatologia'), ('BMF', 'Bucomaxilofacial'), ('CV', 'Cirurgia Vascular'), ('PED', 'Pediatria'), ('INT', 'Internação'), ('OUT', 'Outros')], max_length=10, null=True, verbose_name='Especialidade FAU'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hora_primeiro_atendimento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do 1º Atendimento na FAU'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_registro',
            field=models.CharField(max_length=20, unique=True, verbose_name='RH (Registro Hospitalar)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='risco',
            field=models.CharField(choices=[('Vermelho', 'Vermelho'), ('Laranja', 'Laranja'), ('Amarelo', 'Amarelo'), ('Verde', 'Verde'), ('Azul', 'Azul'), ('Branco', 'Branco')], max_length=10, verbose_name='Classificação de Risco'),
        ),
        migrations.DeleteModel(
            name='AtendimentoSolicitado',
        ),
        migrations.DeleteModel(
            name='ExameSolicitado',
        ),
    ]
