# Generated by Django 5.2.1 on 2025-05-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_paciente_atendimentos_solicitados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidades_concluidas',
            field=models.ManyToManyField(blank=True, related_name='pacientes_concluidos', to='pacientes.especialidade'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidades_pendentes',
            field=models.ManyToManyField(blank=True, related_name='pacientes_pendentes', to='pacientes.especialidade'),
        ),
    ]
