# Generated by Django 5.2.1 on 2025-05-24 20:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_especialidade_paciente_especialidades_concluidas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='especialidades_pendentes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='especialidades_concluidas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidades_pendentes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CG', 'Clínica Geral'), ('NCR', 'Neurocirurgia'), ('TM', 'Traumatologia'), ('BMF', 'Bucomaxilofacial'), ('CV', 'Cirurgia Vascular'), ('PED', 'Pediatria'), ('INT', 'Internação'), ('OUT', 'Outros')], max_length=28, verbose_name='Especialidades Pós 1º Atendimento'),
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidades_concluidas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CG', 'Clínica Geral'), ('NCR', 'Neurocirurgia'), ('TM', 'Traumatologia'), ('BMF', 'Bucomaxilofacial'), ('CV', 'Cirurgia Vascular'), ('PED', 'Pediatria'), ('INT', 'Internação'), ('OUT', 'Outros')], max_length=28, verbose_name='Especialidades Concluídas'),
        ),
    ]
