# Generated by Django 5.2.1 on 2025-05-26 20:22

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_paciente_especialidades_pendentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='exames',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RX', 'Raio-X'), ('TC', 'Tomografia Computadorizada'), ('LAB', 'Laboratório')], max_length=9, verbose_name='Exames Solicitados'),
        ),
    ]
