# Generated by Django 5.2.1 on 2025-05-26 20:33

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_exames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='exames',
        ),
        migrations.AddField(
            model_name='paciente',
            name='exames_concluidos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RX', 'Raio-X'), ('TC', 'Tomografia Computadorizada'), ('LAB', 'Laboratório')], max_length=9, verbose_name='Exames Solicitados'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='exames_pendentes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RX', 'Raio-X'), ('TC', 'Tomografia Computadorizada'), ('LAB', 'Laboratório')], max_length=9, verbose_name='Exames Concluídos'),
        ),
    ]
