# Generated by Django 5.2.1 on 2025-05-26 21:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_remove_paciente_exames_paciente_exames_concluidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='enfermagem_concluidos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ADM', 'Administração de Medicamentos'), ('SAE', 'SAE - Sistematização da Assistência de Enfermagem')], max_length=7, verbose_name='Enfermagem Concluídos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermagem_pendentes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ADM', 'Administração de Medicamentos'), ('SAE', 'SAE - Sistematização da Assistência de Enfermagem')], max_length=7, verbose_name='Enfermagem Solicitados'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='procedimentos_concluidos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SWAB', 'SWAB'), ('ECG', 'ECG')], max_length=8, verbose_name='Procedimentos Concluídos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='procedimentos_pendentes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SWAB', 'SWAB'), ('ECG', 'ECG')], max_length=8, verbose_name='Procedimentos Solicitados'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='solicitacoes_concluidos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BC', 'Boletim de Comunicação')], max_length=2, verbose_name='Solicitações Concluídas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='solicitacoes_pendentes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BC', 'Boletim de Comunicação')], max_length=2, verbose_name='Solicitações Pendentes'),
        ),
    ]
